### ISSUE TITLE
Add src folder.

### ISSUE THREAD

**Issue by jameshalgren** [MESH-Team/MESH_Code_irregular#1]
#### Suggestion:
The project files for a particular development environment (e.g., *.cpb) probably should be separated into a different folder ('ide', perhaps).

**Comment by nazmulazim** [comment]
Thanks James. Maybe the project file is not needed here and I added them unintentionally. As I understand, they are also dependent on the compiler. I shall remove them.

**Comment by nazmulazim** [comment]
Thanks James. Maybe the project file is not needed here and I added them unintentionally. As I understand, they are also dependent on the compiler. I shall remove them.

**Comment by jameshalgren** [comment]
sounds great.
